### ISSUE TITLE
Added to plugin section of parent pom, but nothing happens

### ISSUE THREAD

**Issue by Manfred73** [skuzzle/restrict-imports-enforcer-rule#41]
Hi,

My goal is to fail the build if there are any JUnit4 imports present in my test code.

I've added the following configuration (see below) to pluginManagement section of my parent pom, but when I run a child project which contains org.junit.Test (which is configured as bannedImport), nothing happens and the build is succesful.

I've also tried defining the plugin in the plugin section instead of the pluginManagement section, and I also tried copying the plugin to the child project. The result is the same.

In all cases I do see the Maven output:

[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce **(check-junit4-imports)** @ myproject ---

I've also tried with a regulular package containing classes (instead of test classes) and also here nothing happens. Build is always successful.

What am I missing here. My configuration is as follows:

```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-enforcer-plugin</artifactId>
	<dependencies>
		<dependency>
			<groupId>de.skuzzle.enforcer</groupId>
			<artifactId>restrict-imports-enforcer-rule</artifactId>
			<version>1.0.1</version>
		</dependency>
	</dependencies>
	<executions>
		<execution>
			<id>check-junit4-imports</id>
			<phase>process-sources</phase>
			<goals>
				<goal>enforce</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<rules>
			<restrictImports implementation="de.skuzzle.enforcer.restrictimports.rule.RestrictImports">
				<includeTestCode>true</includeTestCode>
				<reason>Gebruik geen JUnit 4 imports; gebruik in plaatst daarvan JUnit 5 imports</reason>
				<!-- JUnit 4 classes met static methoden -->
				<bannedImport>static org.junit.Assert.*</bannedImport>
				<bannedImport>static org.junit.Assume.*</bannedImport>
				<bannedImport>org.junit.AssumptionViolatedException.*</bannedImport>
				<!-- JUnit 4 interfaces -->
				<bannedImport>org.junit.After</bannedImport>
				<bannedImport>org.junit.AfterClass</bannedImport>
				<bannedImport>org.junit.Before</bannedImport>
				<bannedImport>org.junit.BeforeClass</bannedImport>
				<bannedImport>org.junit.ClassRule</bannedImport>
				<bannedImport>org.junit.FixMethodOrder</bannedImport>
				<bannedImport>org.junit.Ignore</bannedImport>
				<bannedImport>org.junit.Rule</bannedImport>
				<bannedImport>org.junit.Test</bannedImport>
				<!-- JUnit 4 packages -->
				<bannedImport>org.junit.ComparisonFailure.**</bannedImport>
				<bannedImport>org.junit.experimental.**</bannedImport>
				<bannedImport>org.junit.matchers.**</bannedImport>
				<bannedImport>org.junit.rules.**</bannedImport>
				<bannedImport>org.junit.runner.**</bannedImport>
				<bannedImport>org.junit.runners.**</bannedImport>
				<bannedImport>org.junit.validator.**</bannedImport>
			</restrictImports>
		</rules>
	</configuration>
</plugin>
```

**Comment by skuzzle** [comment]
When using multiple `<bannedImport>` statements you have to wrap them in a `<bannedImports>` tag. Could you please try that and report back?

**Comment by Manfred73** [comment]
> When using multiple `<bannedImport>` statements you have to wrap them in a `<bannedImports>` tag. Could you please try that and report back?

I should have seen that ;-) Thanks for pointing out. Adding the <bannedImports> solved it.

**Comment by Manfred73** [comment]
Issue solved. See previous comment.
