### ISSUE TITLE
Feature request: exclude generate-sources and/or generate-test-sources

### ISSUE THREAD

**Issue by honnix** [skuzzle/restrict-imports-enforcer-rule#47]
A maven plugin or annotation processor may generate code using imports that we normally ban, and it is not possible to control the code generation.

It would be nice we can ignore a whole directory such as `target/generated-sources`. I understand this can be done on package level, but sometimes we have generated code and human written code in the same package but different directories.

**Comment by skuzzle** [comment]
Will be released as `1.3.0`
