### ISSUE TITLE
Use widely spread 'Ant style' patterns instead of custom package pattern implementation

### ISSUE THREAD

**Issue by skuzzle** [skuzzle/restrict-imports-enforcer-rule#5]
Consider using the typical Ant patterns for matching package names. Not sure though whether the flexibility is acutally necessary. Could as well use regex pattern for total flexibility.

**Comment by skuzzle** [comment]
Double wildcards are now allowed everywhere within a pattern. They reluctantly match package name parts until a part occurs which matches the pattern part after the `**`.

To be released in 0.8.0

**Comment by ningzhangnj** [comment]
When will 0.8.0 be released?  This feature is really useful.

**Comment by skuzzle** [comment]
I've just released the version. It may take a few hours until it is available from maven central
