### ISSUE TITLE
Support for ignoring classes that cannot be fixed

### ISSUE THREAD

**Issue by hazendaz** [skuzzle/restrict-imports-enforcer-rule#63]
See https://github.com/gaul/modernizer-maven-plugin/tree/master/modernizer-maven-annotations for example.

Currently if a specific class has a restricted import that cannot be addressed such as some usage of spring jdbc extended logic that forces imports on say commons logging due to required overrides, we must turn this completely off.  That loses the point entirely due to one class.  It would be better to have ability to add an annotation to a class similar to done with modernizer maven annotations project does for similar reasons.  I have no experience doing that, but given the example above, I'd be more than happy to help contribute to make this happen.

For my usage, I am one of the leads on a very large supporting devops team and we try to enforce best practice across 2k+ repos.  We use this and have ability to turn off and on globally per project and try to discourage class usage that conflicts.  Currently we are also starting to to block all junit 4 or before usage but some things like junit4 rules are harder to deal with when entirely customized and tools like open rewrite are unable to magically rewrite them.  Having such an annotation to scan and skip looking on listed classes is a modern way to do this and would greatly benefit in our goal if blocking all junit 4 as possible without entirely turning this off.

**Comment by skuzzle** [comment]
I've linked a pull request that will solve this issue via an XML configuration as outlined in my previous comment. Feel free to leave some feedback. I'm not especially happy with the naming yet so that's likely subject to some change.

**Comment by hazendaz** [comment]
Added feedback on PR.

**Comment by skuzzle** [comment]
If you want to give it a try: this feature can already be tried out using the recently released `2.4.0-rc1` version of the rule

**Comment by skuzzle** [comment]
Released in 2.4.0
