### ISSUE TITLE
Add support for fully qualified names for annotations

### ISSUE THREAD

**Issue by yeikel** [skuzzle/restrict-imports-enforcer-rule#79]
I understand that the goal of this library is to support imports exclusively, but would this request fall under this project or should I look for other solutions?

Example

```java
 @com.couchbase.client.core.deps.com.google.common.annotations.VisibleForTesting
private DataAccessFactory() {
    
```

This only works if it is is imported explicitly. 

`import com.couchbase.client.core.deps.com.google.common.annotations.VisibleForTesting`

**Comment by skuzzle** [comment]
Good find. This should be fairly easy to implement given that we already have support for full qualified class usage since #57
It is just a special case that is currently not covered.
I'll have a look into this tomorrow. 

This would also be a good issue for a first contribution 😉
